# Workflow that can push my image into docker hub to every push in the directory

name: CI to Docker Hub

# Controls when the workflow will run when there is an update in the master 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# define my jobs
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repo
      - uses: actions/checkout@v2
      
      # Login into docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # Setup the tool to build the image
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      # Build and push the image
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node-docker:latest
      
      # Show digests
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
